#!/bin/bash

if ! git help --all | grep -q flow; then
    echo "Please install git-flow extension first. See the README.md file for details."
    exit 1
else
    echo -n "Initialising git-flow configuration... "
    git config gitflow.branch.master "master"
    git config gitflow.branch.develop "trunk"
    git config gitflow.prefix.feature "feature/"
    git config gitflow.prefix.release "release/"
    git config gitflow.prefix.hotfix "hotfix/"
    git config gitflow.prefix.support "support/"
    git config gitflow.prefix.versiontag ""
    echo "done."
fi
